services:
  bill-alarm:
    image: ghcr.io/ysya/bill-alarm:main
    ports:
      - "3100:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
